#
# Automatically generated file. DO NOT MODIFY
#

PRODUCT_SOONG_NAMESPACES += \
    vendor/lge/judyln-common

PRODUCT_COPY_FILES += \
    vendor/lge/judyln-common/proprietary/vendor/etc/acdbdata/Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Bluetooth_cal.acdb \
    vendor/lge/judyln-common/proprietary/vendor/etc/acdbdata/Codec_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Codec_cal.acdb \
    vendor/lge/judyln-common/proprietary/vendor/etc/acdbdata/General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/General_cal.acdb \
    vendor/lge/judyln-common/proprietary/vendor/etc/acdbdata/Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Global_cal.acdb \
    vendor/lge/judyln-common/proprietary/vendor/etc/acdbdata/Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Handset_cal.acdb \
    vendor/lge/judyln-common/proprietary/vendor/etc/acdbdata/Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Hdmi_cal.acdb \
    vendor/lge/judyln-common/proprietary/vendor/etc/acdbdata/Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Headset_cal.acdb \
    vendor/lge/judyln-common/proprietary/vendor/etc/acdbdata/Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Speaker_cal.acdb \
    vendor/lge/judyln-common/proprietary/vendor/etc/camera/camera_tune_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/camera_tune_config.xml \
    vendor/lge/judyln-common/proprietary/vendor/etc/camera/vnr/SJ_VideoNR_LUT.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/vnr/SJ_VideoNR_LUT.bin \
    vendor/lge/judyln-common/proprietary/vendor/etc/init/android.hardware.keymaster@3.0-service-qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.keymaster@3.0-service-qti.rc \
    vendor/lge/judyln-common/proprietary/vendor/etc/init/vendor.qti.hardware.sensorscalibrate@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.sensorscalibrate@1.0-service.rc \
    vendor/lge/judyln-common/proprietary/vendor/etc/libnfc-nci.conf:$(TARGET_COPY_OUT_VENDOR)/etc/libnfc-nci.conf \
    vendor/lge/judyln-common/proprietary/vendor/etc/libnfc-nxp.conf:$(TARGET_COPY_OUT_VENDOR)/etc/libnfc-nxp.conf \
    vendor/lge/judyln-common/proprietary/vendor/etc/permissions/vendor-qti-hardware-sensorscalibrate.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/vendor-qti-hardware-sensorscalibrate.xml \
    vendor/lge/judyln-common/proprietary/vendor/etc/qdcm_calib_data_SW49410_1440_3120_cmd_mode_dsc_dsi_panel.xml:$(TARGET_COPY_OUT_VENDOR)/etc/qdcm_calib_data_SW49410_1440_3120_cmd_mode_dsc_dsi_panel.xml \
    vendor/lge/judyln-common/proprietary/vendor/etc/scve/facereco/gModel.dat:$(TARGET_COPY_OUT_VENDOR)/etc/scve/facereco/gModel.dat \
    vendor/lge/judyln-common/proprietary/vendor/etc/sensors/hals.conf:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/hals.conf \
    vendor/lge/judyln-common/proprietary/vendor/etc/sensors/registry/config/ak991x_dri_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/ak991x_dri_0.json \
    vendor/lge/judyln-common/proprietary/vendor/etc/sensors/registry/config/apds9160_0_reva.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/apds9160_0_reva.json \
    vendor/lge/judyln-common/proprietary/vendor/etc/sensors/registry/config/apds9160_0_revc.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/apds9160_0_revc.json \
    vendor/lge/judyln-common/proprietary/vendor/etc/sensors/registry/config/apds9160_0_revd_sub1.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/apds9160_0_revd_sub1.json \
    vendor/lge/judyln-common/proprietary/vendor/etc/sensors/registry/config/apds9160_0_revd_sub2.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/apds9160_0_revd_sub2.json \
    vendor/lge/judyln-common/proprietary/vendor/etc/sensors/registry/config/apds9939_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/apds9939_0.json \
    vendor/lge/judyln-common/proprietary/vendor/etc/sensors/registry/config/bmp285_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/bmp285_0.json \
    vendor/lge/judyln-common/proprietary/vendor/etc/sensors/registry/config/etc_version:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/etc_version \
    vendor/lge/judyln-common/proprietary/vendor/etc/sensors/registry/config/icm4x6xx_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/icm4x6xx_0.json \
    vendor/lge/judyln-common/proprietary/vendor/etc/sensors/registry/config/icm4x6xx_0_reva.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/icm4x6xx_0_reva.json \
    vendor/lge/judyln-common/proprietary/vendor/etc/sensors/registry/config/lsm6ds3_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/lsm6ds3_0.json \
    vendor/lge/judyln-common/proprietary/vendor/etc/sensors/registry/config/lsm6dsm_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/lsm6dsm_0.json \
    vendor/lge/judyln-common/proprietary/vendor/etc/sensors/registry/config/sdm845_ak991x_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sdm845_ak991x_0.json \
    vendor/lge/judyln-common/proprietary/vendor/etc/sensors/registry/config/sdm845_apds9160_0_reva.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sdm845_apds9160_0_reva.json \
    vendor/lge/judyln-common/proprietary/vendor/etc/sensors/registry/config/sdm845_apds9160_0_reva_sub1.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sdm845_apds9160_0_reva_sub1.json \
    vendor/lge/judyln-common/proprietary/vendor/etc/sensors/registry/config/sdm845_apds9160_0_reva_sub2.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sdm845_apds9160_0_reva_sub2.json \
    vendor/lge/judyln-common/proprietary/vendor/etc/sensors/registry/config/sdm845_apds9939_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sdm845_apds9939_0.json \
    vendor/lge/judyln-common/proprietary/vendor/etc/sensors/registry/config/sdm845_bmp285_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sdm845_bmp285_0.json \
    vendor/lge/judyln-common/proprietary/vendor/etc/sensors/registry/config/sdm845_icm4x6xx_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sdm845_icm4x6xx_0.json \
    vendor/lge/judyln-common/proprietary/vendor/etc/sensors/registry/config/sdm845_icm4x6xx_0_reva.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sdm845_icm4x6xx_0_reva.json \
    vendor/lge/judyln-common/proprietary/vendor/etc/sensors/registry/config/sdm845_lsm6dsm_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sdm845_lsm6dsm_0.json \
    vendor/lge/judyln-common/proprietary/vendor/etc/sensors/registry/config/sdm845_power_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sdm845_power_0.json \
    vendor/lge/judyln-common/proprietary/vendor/etc/sensors/registry/config/sdm845_spl06_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sdm845_spl06_0.json \
    vendor/lge/judyln-common/proprietary/vendor/etc/sensors/registry/config/sdm845_tmx4903.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sdm845_tmx4903.json \
    vendor/lge/judyln-common/proprietary/vendor/etc/sensors/registry/config/sensors_list.txt:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sensors_list.txt \
    vendor/lge/judyln-common/proprietary/vendor/etc/sensors/registry/config/sns_amd.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sns_amd.json \
    vendor/lge/judyln-common/proprietary/vendor/etc/sensors/registry/config/sns_amd_sw_disabled.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sns_amd_sw_disabled.json \
    vendor/lge/judyln-common/proprietary/vendor/etc/sensors/registry/config/sns_amd_sw_enabled.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sns_amd_sw_enabled.json \
    vendor/lge/judyln-common/proprietary/vendor/etc/sensors/registry/config/sns_basic_gestures.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sns_basic_gestures.json \
    vendor/lge/judyln-common/proprietary/vendor/etc/sensors/registry/config/sns_bring_to_ear.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sns_bring_to_ear.json \
    vendor/lge/judyln-common/proprietary/vendor/etc/sensors/registry/config/sns_cm.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sns_cm.json \
    vendor/lge/judyln-common/proprietary/vendor/etc/sensors/registry/config/sns_device_orient.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sns_device_orient.json \
    vendor/lge/judyln-common/proprietary/vendor/etc/sensors/registry/config/sns_diag_filter.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sns_diag_filter.json \
    vendor/lge/judyln-common/proprietary/vendor/etc/sensors/registry/config/sns_distance_bound.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sns_distance_bound.json \
    vendor/lge/judyln-common/proprietary/vendor/etc/sensors/registry/config/sns_dpc.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sns_dpc.json \
    vendor/lge/judyln-common/proprietary/vendor/etc/sensors/registry/config/sns_facing.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sns_facing.json \
    vendor/lge/judyln-common/proprietary/vendor/etc/sensors/registry/config/sns_fmv.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sns_fmv.json \
    vendor/lge/judyln-common/proprietary/vendor/etc/sensors/registry/config/sns_geomag_rv.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sns_geomag_rv.json \
    vendor/lge/judyln-common/proprietary/vendor/etc/sensors/registry/config/sns_gyro_cal.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sns_gyro_cal.json \
    vendor/lge/judyln-common/proprietary/vendor/etc/sensors/registry/config/sns_lg_filtered_pressure.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sns_lg_filtered_pressure.json \
    vendor/lge/judyln-common/proprietary/vendor/etc/sensors/registry/config/sns_lg_gated_gyro.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sns_lg_gated_gyro.json \
    vendor/lge/judyln-common/proprietary/vendor/etc/sensors/registry/config/sns_mag_cal.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sns_mag_cal.json \
    vendor/lge/judyln-common/proprietary/vendor/etc/sensors/registry/config/sns_multishake.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sns_multishake.json \
    vendor/lge/judyln-common/proprietary/vendor/etc/sensors/registry/config/sns_pedometer.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sns_pedometer.json \
    vendor/lge/judyln-common/proprietary/vendor/etc/sensors/registry/config/sns_rmd.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sns_rmd.json \
    vendor/lge/judyln-common/proprietary/vendor/etc/sensors/registry/config/sns_rotv.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sns_rotv.json \
    vendor/lge/judyln-common/proprietary/vendor/etc/sensors/registry/config/sns_smd.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sns_smd.json \
    vendor/lge/judyln-common/proprietary/vendor/etc/sensors/registry/config/sns_tilt.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sns_tilt.json \
    vendor/lge/judyln-common/proprietary/vendor/etc/sensors/registry/config/sns_tilt_sw_disabled.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sns_tilt_sw_disabled.json \
    vendor/lge/judyln-common/proprietary/vendor/etc/sensors/registry/config/sns_tilt_sw_enabled.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sns_tilt_sw_enabled.json \
    vendor/lge/judyln-common/proprietary/vendor/etc/sensors/registry/config/sns_tilt_to_wake.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sns_tilt_to_wake.json \
    vendor/lge/judyln-common/proprietary/vendor/etc/sensors/registry/config/sns_window_orientation.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sns_window_orientation.json \
    vendor/lge/judyln-common/proprietary/vendor/etc/sensors/registry/config/spl06_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/spl06_0.json \
    vendor/lge/judyln-common/proprietary/vendor/etc/sensors/registry/config/tmx4903.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/tmx4903.json \
    vendor/lge/judyln-common/proprietary/vendor/etc/sensors/registry/registry/sensors_registry:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/registry/sensors_registry \
    vendor/lge/judyln-common/proprietary/vendor/etc/sensors/registry/registry/sensors_settings:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/registry/sensors_settings \
    vendor/lge/judyln-common/proprietary/vendor/etc/sensors/registry/sns_reg_config:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/sns_reg_config \
    vendor/lge/judyln-common/proprietary/vendor/etc/sensors/sns_reg_config:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/sns_reg_config \
    vendor/lge/judyln-common/proprietary/vendor/etc/wifi/GLOBAL/bdwlan.bin:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/GLOBAL/bdwlan.bin \
    vendor/lge/judyln-common/proprietary/vendor/etc/wifi/GLOBAL/bdwlan_ch0.bin:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/GLOBAL/bdwlan_ch0.bin \
    vendor/lge/judyln-common/proprietary/vendor/etc/wifi/GLOBAL/bdwlan_ch1.bin:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/GLOBAL/bdwlan_ch1.bin \
    vendor/lge/judyln-common/proprietary/vendor/etc/wifi/aoa_cldb_falcon.bin:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/aoa_cldb_falcon.bin \
    vendor/lge/judyln-common/proprietary/vendor/etc/wifi/aoa_cldb_swl14.bin:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/aoa_cldb_swl14.bin \
    vendor/lge/judyln-common/proprietary/vendor/ffu/FFUSAMSUNG_KLUDG4U1EA-B0C1_0500.bin:$(TARGET_COPY_OUT_VENDOR)/ffu/FFUSAMSUNG_KLUDG4U1EA-B0C1_0500.bin \
    vendor/lge/judyln-common/proprietary/vendor/ffu/FFUTOSHIBA_THGAF8G9T43BAIRB_0300.bin:$(TARGET_COPY_OUT_VENDOR)/ffu/FFUTOSHIBA_THGAF8G9T43BAIRB_0300.bin \
    vendor/lge/judyln-common/proprietary/vendor/firmware/CAMERA_ICP.elf:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.elf \
    vendor/lge/judyln-common/proprietary/vendor/firmware/Tfa9872.cnt:$(TARGET_COPY_OUT_VENDOR)/firmware/Tfa9872.cnt \
    vendor/lge/judyln-common/proprietary/vendor/firmware/crbtfw21.tlv:$(TARGET_COPY_OUT_VENDOR)/firmware/crbtfw21.tlv \
    vendor/lge/judyln-common/proprietary/vendor/firmware/crnv21.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/crnv21.bin \
    vendor/lge/judyln-common/proprietary/vendor/firmware/leia_pfp_470.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/leia_pfp_470.fw \
    vendor/lge/judyln-common/proprietary/vendor/firmware/leia_pm4_470.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/leia_pm4_470.fw \
    vendor/lge/judyln-common/proprietary/vendor/lib/camera/com.qti.sensormodule.imx351.bin:$(TARGET_COPY_OUT_VENDOR)/lib/camera/com.qti.sensormodule.imx351.bin \
    vendor/lge/judyln-common/proprietary/vendor/lib/camera/com.qti.sensormodule.imx351_wide.bin:$(TARGET_COPY_OUT_VENDOR)/lib/camera/com.qti.sensormodule.imx351_wide.bin \
    vendor/lge/judyln-common/proprietary/vendor/lib/camera/com.qti.sensormodule.sl846.bin:$(TARGET_COPY_OUT_VENDOR)/lib/camera/com.qti.sensormodule.sl846.bin \
    vendor/lge/judyln-common/proprietary/vendor/lib/camera/com.qti.tuned.default.bin:$(TARGET_COPY_OUT_VENDOR)/lib/camera/com.qti.tuned.default.bin \
    vendor/lge/judyln-common/proprietary/vendor/lib/camera/com.qti.tuned.imx351.bin:$(TARGET_COPY_OUT_VENDOR)/lib/camera/com.qti.tuned.imx351.bin \
    vendor/lge/judyln-common/proprietary/vendor/lib/camera/com.qti.tuned.imx351_wide.bin:$(TARGET_COPY_OUT_VENDOR)/lib/camera/com.qti.tuned.imx351_wide.bin \
    vendor/lge/judyln-common/proprietary/vendor/lib/camera/com.qti.tuned.sl846.bin:$(TARGET_COPY_OUT_VENDOR)/lib/camera/com.qti.tuned.sl846.bin \
    vendor/lge/judyln-common/proprietary/vendor/lib/camera/fdconfigpreview.bin:$(TARGET_COPY_OUT_VENDOR)/lib/camera/fdconfigpreview.bin \
    vendor/lge/judyln-common/proprietary/vendor/lib/camera/fdconfigpreviewlite.bin:$(TARGET_COPY_OUT_VENDOR)/lib/camera/fdconfigpreviewlite.bin \
    vendor/lge/judyln-common/proprietary/vendor/lib/camera/fdconfigvideo.bin:$(TARGET_COPY_OUT_VENDOR)/lib/camera/fdconfigvideo.bin \
    vendor/lge/judyln-common/proprietary/vendor/lib/camera/fdconfigvideolite.bin:$(TARGET_COPY_OUT_VENDOR)/lib/camera/fdconfigvideolite.bin \
    vendor/lge/judyln-common/proprietary/vendor/lib/camera/fw/bu24235_dl_program_JUDY_JOAN_LGITAct_ICG1020S_rev0_S_data1.bin:$(TARGET_COPY_OUT_VENDOR)/lib/camera/fw/bu24235_dl_program_JUDY_JOAN_LGITAct_ICG1020S_rev0_S_data1.bin \
    vendor/lge/judyln-common/proprietary/vendor/lib/camera/fw/bu24235_dl_program_JUDY_JOAN_LGITAct_ICG1020S_rev0_S_data2.bin:$(TARGET_COPY_OUT_VENDOR)/lib/camera/fw/bu24235_dl_program_JUDY_JOAN_LGITAct_ICG1020S_rev0_S_data2.bin \
    vendor/lge/judyln-common/proprietary/vendor/lib/camera/fw/bu24235_dl_program_Judy_LGITAct_ICG1020S_rev0_S_data1.bin:$(TARGET_COPY_OUT_VENDOR)/lib/camera/fw/bu24235_dl_program_Judy_LGITAct_ICG1020S_rev0_S_data1.bin \
    vendor/lge/judyln-common/proprietary/vendor/lib/camera/fw/bu24235_dl_program_Judy_LGITAct_ICG1020S_rev0_S_data2.bin:$(TARGET_COPY_OUT_VENDOR)/lib/camera/fw/bu24235_dl_program_Judy_LGITAct_ICG1020S_rev0_S_data2.bin \
    vendor/lge/judyln-common/proprietary/vendor/lib/camera/fw/bu24235_dl_program_Judy_emma_LGIT_ICG1020S_rev1_S_data1.bin:$(TARGET_COPY_OUT_VENDOR)/lib/camera/fw/bu24235_dl_program_Judy_emma_LGIT_ICG1020S_rev1_S_data1.bin \
    vendor/lge/judyln-common/proprietary/vendor/lib/camera/fw/bu24235_dl_program_Judy_emma_LGIT_ICG1020S_rev1_S_data2.bin:$(TARGET_COPY_OUT_VENDOR)/lib/camera/fw/bu24235_dl_program_Judy_emma_LGIT_ICG1020S_rev1_S_data2.bin \
    vendor/lge/judyln-common/proprietary/vendor/lib/camera/titan17x_usecases.bin:$(TARGET_COPY_OUT_VENDOR)/lib/camera/titan17x_usecases.bin

PRODUCT_PACKAGES += \
    audio.primary.judyln \
    libaudio_log_utils \
    com.qti.eisv2 \
    com.qti.eisv3 \
    com.qti.stats.aec \
    com.qti.stats.af \
    com.qti.stats.afd \
    com.qti.stats.asd \
    com.qti.stats.awb \
    com.qti.stats.pdlib \
    com.qti.stats.pdlibsony \
    com.qti.stats.pdlibwrapper \
    fingerprint.sdm845 \
    vendor.qti.hardware.sensorscalibrate@1.0-impl \
    libgf_algo \
    libgf_hal \
    libmmcamera_faceproc \
    libmmcamera_faceproc2 \
    libscveFaceLandmarks \
    libscveFaceRecognition \
    libsensor_lge_cal \
    libsensorcal \
    libsensorslog \
    libsns_device_mode_stub \
    libsns_fastRPC_util \
    libsns_low_lat_stream_stub \
    libsnsapi \
    libsnsdiaglog \
    libssc \
    libsymphony-1.1.4 \
    libsymphonypower-1.1.4 \
    sensors.sar \
    sensors.ssc \
    vendor.qti.hardware.sensorscalibrate@1.0 \
    com.qti.sensor.imx351 \
    com.qti.sensor.imx351_wide \
    com.qti.sensor.sl846 \
    com.lge.node.camerasolution \
    com.lge.node.capturebokeh \
    com.lge.node.elpis \
    com.lge.node.elvis \
    com.lge.node.hdr \
    com.lge.node.lavis \
    com.lge.node.multiframe \
    com.lge.node.realtimebokeh \
    com.lge.node.warp \
    com.lge.stats.aec \
    com.lge.stats.aecwrapper \
    com.lge.stats.af \
    com.lge.stats.af_core \
    com.lge.stats.awb \
    com.qti.hvx.addconstant \
    com.qti.hvx.binning \
    com.qti.node.dummyrtb \
    com.qti.node.dummysat \
    com.qti.node.eisv2 \
    com.qti.node.eisv3 \
    com.qti.node.gpu \
    com.qti.node.memcpy \
    com.qti.node.remosaic \
    com.qti.node.stich \
    com.qti.node.swregistration \
    com.qti.stats.awbwrapper \
    com.qtistatic.stats.aec \
    com.qtistatic.stats.af \
    com.qtistatic.stats.awb \
    com.qtistatic.stats.pdlib \
    liblg_aec_param_imx351_binning_preview \
    liblg_aec_param_imx351_binning_video \
    liblg_aec_param_imx351_cine_video \
    liblg_aec_param_imx351_hfr_120 \
    liblg_aec_param_imx351_hfr_240 \
    liblg_aec_param_imx351_hfr_60 \
    liblg_aec_param_imx351_hfr_90 \
    liblg_aec_param_imx351_out_focus \
    liblg_aec_param_imx351_panorama \
    liblg_aec_param_imx351_preview \
    liblg_aec_param_imx351_sensor_hdr_auto_preview \
    liblg_aec_param_imx351_sensor_hdr_auto_video \
    liblg_aec_param_imx351_sensor_hdr_on_preview \
    liblg_aec_param_imx351_sensor_hdr_on_video \
    liblg_aec_param_imx351_uhfr_60 \
    liblg_aec_param_imx351_video \
    liblg_aec_param_imx351w_binning_preview \
    liblg_aec_param_imx351w_binning_video \
    liblg_aec_param_imx351w_cine_video \
    liblg_aec_param_imx351w_hfr_120 \
    liblg_aec_param_imx351w_hfr_240 \
    liblg_aec_param_imx351w_hfr_60 \
    liblg_aec_param_imx351w_hfr_90 \
    liblg_aec_param_imx351w_out_focus \
    liblg_aec_param_imx351w_panorama \
    liblg_aec_param_imx351w_preview \
    liblg_aec_param_imx351w_sensor_hdr_auto_preview \
    liblg_aec_param_imx351w_sensor_hdr_auto_video \
    liblg_aec_param_imx351w_sensor_hdr_on_preview \
    liblg_aec_param_imx351w_sensor_hdr_on_video \
    liblg_aec_param_imx351w_uhfr_60 \
    liblg_aec_param_imx351w_video \
    liblg_awb_param_imx351n_food \
    liblg_awb_param_imx351n_liveshot \
    liblg_awb_param_imx351n_outfocus \
    liblg_awb_param_imx351n_panorama_lg \
    liblg_awb_param_imx351n_preview \
    liblg_awb_param_imx351n_rec_cinema \
    liblg_awb_param_imx351n_rec_food \
    liblg_awb_param_imx351n_rec_outfocus \
    liblg_awb_param_imx351n_rec_sum_binning \
    liblg_awb_param_imx351n_snapshot \
    liblg_awb_param_imx351n_sum_binning \
    liblg_awb_param_imx351n_video \
    liblg_awb_param_imx351n_zsl \
    liblg_awb_param_imx351w_food \
    liblg_awb_param_imx351w_liveshot \
    liblg_awb_param_imx351w_outfocus \
    liblg_awb_param_imx351w_panorama_lg \
    liblg_awb_param_imx351w_preview \
    liblg_awb_param_imx351w_rec_cinema \
    liblg_awb_param_imx351w_rec_food \
    liblg_awb_param_imx351w_rec_outfocus \
    liblg_awb_param_imx351w_rec_sum_binning \
    liblg_awb_param_imx351w_snapshot \
    liblg_awb_param_imx351w_sum_binning \
    liblg_awb_param_imx351w_video \
    liblg_awb_param_imx351w_zsl \
    camera.sdm845 \
    com.qti.chi.override \
    lib.com.lge.elvis \
    libAutoContrast \
    libSJVideoNR \
    lib_wdr2 \
    libarcsoft_beauty_picselfie \
    libarcsoft_dualcam_refocus \
    libarcsoft_picselfie_algorithm \
    libbwfocuspeaking \
    libcamxfdalgov7 \
    libcamxfdengine \
    libcamxstatscore \
    libcamxtintlessalgo \
    libcinemaeffect \
    libcom.qti.chinodeutils \
    libfilm_emulation \
    libfilm_emulation_symphony \
    liblgae_main \
    liblgawb_main \
    liblgdnn \
    liblghdri \
    libmorpho_image_stab31 \
    libmorpho_superzoom \
    libmpbase \
    libpn553_fw \
    sensors.hal.tof \
    com.qti.stats.haf \
    com.qti.stats.localhistogram \
    libpn553_fw_64 \
    chre \
    vendor.qti.hardware.sensorscalibrate@1.0-service \
    sensors.qti \
    sscrpcd

PRODUCT_PACKAGES += \
    vendor_firmware_wlan_qca_cld_bdwlan_bin \
    vendor_firmware_wlan_qca_cld_bdwlan_ch0_bin \
    vendor_firmware_wlan_qca_cld_bdwlan_ch1_bin
